#!/usr/bin/env node
import { readFileSync, writeFileSync, existsSync } from 'fs'
import { fileURLToPath } from 'url'
import { dirname, join } from 'path'
import * as readline from 'readline'

const __dirname = dirname(fileURLToPath(import.meta.url))
const templateDir = join(__dirname, '../templates')

console.log('📝 Генерация стартового README.md...')

// Функция для интерактивного вопроса
function askQuestion(query) {
  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  })

  return new Promise((resolve) =>
    rl.question(query, (ans) => {
      rl.close()
      resolve(ans)
    })
  )
}

// Проверяем существование README
if (existsSync('README.md')) {
  const answer = await askQuestion('⚠️  README.md уже существует. Перезаписать? (y/N): ')

  if (answer.toLowerCase() !== 'y' && answer.toLowerCase() !== 'yes') {
    console.log('⏭️  Создание README отменено')
    process.exit(0)
  }

  console.log('✅ README.md будет перезаписан\n')
}

// Читаем package.json
const packageJson = JSON.parse(readFileSync('package.json', 'utf8'))

const projectName = packageJson.name || 'Project'
const description = packageJson.description || 'Описание проекта'
const author = packageJson.author || 'vv0rkz'
const license = packageJson.license || 'MIT'

// Получаем URL репозитория
let repoUrl = ''
if (packageJson.repository?.url) {
  repoUrl = packageJson.repository.url.replace('git+', '').replace('.git', '')
} else {
  repoUrl = `https://github.com/${author}/${projectName}`
}

// Читаем шаблон
const templatePath = join(templateDir, 'README.md')
let readmeContent = ''

if (existsSync(templatePath)) {
  readmeContent = readFileSync(templatePath, 'utf8')

  // Подставляем значения
  readmeContent = readmeContent
    .replace(/\{\{PROJECT_NAME\}\}/g, projectName)
    .replace(/\{\{PROJECT_DESCRIPTION\}\}/g, description)
    .replace(/\{\{REPO_URL\}\}/g, repoUrl)
    .replace(/\{\{AUTHOR\}\}/g, author)
    .replace(/\{\{LICENSE\}\}/g, license)

  console.log('✅ README.md создан из шаблона!')
} else {
  // Fallback если шаблона нет
  readmeContent = `# ${projectName}

${description}

<!-- AUTOGENERATED_SECTION START -->
<!-- AUTOGENERATED_SECTION END -->

## 🔧 Workflow

Проект использует [@vv0rkz/js-template](https://github.com/vv0rkz/js-template)

## 📄 Лицензия

${license} © [${author}](${repoUrl})
`
  console.log('✅ README.md создан (fallback)!')
}

// Сохраняем
writeFileSync('README.md', readmeContent)

console.log('\n📝 Теперь:')
console.log('   1. Отредактируй README.md под свой проект')
console.log('   2. Добавь скриншоты/демо')
console.log('   3. npm run _ update-readme — для обновления истории версий')
