#!/usr/bin/env node
import { readFileSync, writeFileSync, existsSync } from 'fs'

console.log('📝 Генерация стартового README.md...')

// Читаем package.json
const packageJson = JSON.parse(readFileSync('package.json', 'utf8'))

const projectName = packageJson.name
const description = packageJson.description || 'Описание проекта'
const author = packageJson.author || 'vv0rkz'
const license = packageJson.license || 'MIT'
const repoUrl = packageJson.repository?.url?.replace('git+', '').replace('.git', '') || ''

// Минималистичный шаблон README
const readmeTemplate = `# ${projectName}

${description}

## 🚀 Быстрый старт

\`\`\`bash
# Установка зависимостей
npm install

# Запуск
npm run dev
\`\`\`

## 📋 Команды

\`\`\`bash
npm run dev              # Разработка
npm run _ tasks          # Задачи
npm run _ release        # Релиз
\`\`\`

> Проект использует [@vv0rkz/js-template](https://github.com/vv0rkz/js-template) для автоматизации workflow (husky hooks, changelog, GitHub tasks)

<!-- AUTOGENERATED_SECTION START -->
<!-- AUTOGENERATED_SECTION END -->

## 📄 Лицензия

${license} © ${author}
`

// Проверяем существование README
if (existsSync('README.md')) {
  console.log('⚠️  README.md уже существует')
  console.log('💡 Удали файл или переименуй, чтобы создать новый')
  process.exit(1)
}

// Сохраняем README
writeFileSync('README.md', readmeTemplate)
console.log('✅ README.md создан!')
console.log('\n📝 Теперь:')
console.log('   1. Отредактируй описание и добавь детали')
console.log('   2. Добавь скриншоты/демо')
console.log('   3. npm run _ update-readme — для обновления истории версий')
