#!/usr/bin/env node
import { execSync, spawnSync } from 'child_process'
import { platform } from 'os'
import { dirname, join } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const isWin = platform() === 'win32'
const npxCmd = isWin ? 'npx.cmd' : 'npx'

console.log('🚀 Запуск релиза...\n')

// 1. Проверка демо
const checkDemo = spawnSync('node', [join(__dirname, 'check-demo-for-release.js')], { stdio: 'inherit' })
if (checkDemo.status !== 0) {
  console.error('❌ Проверка демо не прошла')
  process.exit(1)
}

// 2. Получаем текущую версию
const currentVersion = JSON.parse(execSync('npm pkg get version', { encoding: 'utf8' })).replace(/"/g, '')
console.log(`📦 Текущая версия: ${currentVersion}`)

// 3. Предупреждение для 0.x.x
if (currentVersion.startsWith('0.')) {
  console.log('\n⚠️  ВНИМАНИЕ: Версия 0.x.x имеет особое поведение!')
  console.log('💡 changelogen для версий < 1.0.0:')
  console.log('   • feat: коммиты → patch bump (0.1.0 → 0.1.1)')
  console.log('   • fix: коммиты → patch bump (0.1.0 → 0.1.1)')
  console.log('   • BREAKING CHANGE → minor bump (0.1.0 → 0.2.0)')
  console.log('')
  console.log('📖 Подробнее: https://github.com/conventional-changelog/standard-version/issues/539')
  console.log('✅ Рекомендация: используй версии ≥ 1.0.0 для правильного semver')
  console.log('   Обнови: npm pkg set version=1.0.0 && git tag v1.0.0\n')
}

// 4. Анализ коммитов
let lastTag = ''
try {
  lastTag = execSync('git describe --tags --abbrev=0', { encoding: 'utf8' }).trim()
  console.log(`📌 Последний тег: ${lastTag}`)
} catch (error) {
  console.log('📌 Теги не найдены (первый релиз)')
}

const commitMessages = lastTag
  ? execSync(`git log ${lastTag}..HEAD --format=%s`, { encoding: 'utf8' })
  : execSync('git log --format=%s -10', { encoding: 'utf8' })

const commits = commitMessages.split('\n').filter(Boolean)

const featCount = commits.filter((c) => c.startsWith('feat:')).length
const fixCount = commits.filter((c) => c.startsWith('fix:')).length
const refactorCount = commits.filter((c) => c.startsWith('refactor:')).length
const perfCount = commits.filter((c) => c.startsWith('perf:')).length
const docsCount = commits.filter((c) => c.startsWith('docs:')).length
const buildCount = commits.filter((c) => c.startsWith('build:')).length

console.log('\n📊 Анализ коммитов:')
if (featCount > 0) console.log(`   ✨ feat: ${featCount}`)
if (fixCount > 0) console.log(`   🐛 fix: ${fixCount}`)
if (refactorCount > 0) console.log(`   ♻️  refactor: ${refactorCount}`)
if (perfCount > 0) console.log(`   ⚡ perf: ${perfCount}`)
if (docsCount > 0) console.log(`   📚 docs: ${docsCount}`)
if (buildCount > 0) console.log(`   🏗️  build: ${buildCount}`)

// 5. Определяем bump type
const isV0 = currentVersion.startsWith('0.')
let bumpType = 'patch'

if (isV0) {
  // Для 0.x.x используем --major чтобы получить minor bump при feat
  bumpType = featCount > 0 ? 'major' : 'patch'
  console.log(`\n🔢 Bump type: ${bumpType === 'major' ? 'major (для 0.x.x это даст minor)' : 'patch'}`)
} else {
  // Для ≥1.0.0 нормальное поведение
  bumpType = featCount > 0 ? 'minor' : 'patch'
  console.log(`\n🔢 Bump type: ${bumpType}`)
}

// 6. Создаём changelog
console.log('\n📝 Создание changelog...')
const changelog = spawnSync(npxCmd, ['changelogen', '--release', `--${bumpType}`], {
  stdio: 'inherit',
})

if (changelog.status !== 0) {
  console.error('\n❌ Ошибка создания changelog')
  console.log('💡 Попробуй вручную: npx changelogen --release')
  process.exit(1)
}

// 7. Обновляем README
console.log('\n📝 Обновление README...')
const updateReadme = spawnSync('node', [join(__dirname, 'update-readme.js')], { stdio: 'inherit' })
if (updateReadme.status !== 0) {
  console.log('⚠️  README не обновлён (возможно нет секции AUTOGENERATED)')
}

console.log('\n✅ Релиз успешно создан!')
console.log('💡 Теперь можно:')
console.log('   npm run _ push-release   # Создать PR и смерджить в main')
