#!/usr/bin/env node
import { execSync } from 'child_process'
import { existsSync, readFileSync } from 'fs'
import { platform } from 'os'
import { loadConfig } from './config.js'

const isWin = platform() === 'win32'
const ghCmd = isWin ? 'gh.exe' : 'gh'

const config = await loadConfig()
const audit = (config.release && config.release.audit) || {}

if (audit.enable === false) process.exit(0)

// When invoked as a pre-run hook we stay silent on a clean repo. Stand-alone
// invocations (`jst audit`) print a positive confirmation.
const quietIfClean = process.argv.includes('--quiet-if-clean')
const warnOnly = audit.warnOnly !== false

function safeExec(cmd) {
  try {
    return execSync(cmd, { encoding: 'utf8', stdio: ['pipe', 'pipe', 'ignore'] }).trim()
  } catch {
    return ''
  }
}

const tagsRaw = safeExec('git tag --sort=-creatordate')
const tags = tagsRaw
  .split('\n')
  .map((t) => t.trim())
  .filter((t) => /^v\d+\.\d+\.\d+$/.test(t))

if (tags.length === 0) process.exit(0)

let releaseTags = new Set()
const releasesJson = safeExec(`${ghCmd} release list --json tagName --limit 100`)
if (releasesJson) {
  try {
    releaseTags = new Set(JSON.parse(releasesJson).map((r) => r.tagName))
  } catch {
    // gh returned non-JSON — treat as "no info", skip the release check
    releaseTags = null
  }
}

const demoCfg = (config.release && config.release.demo) || {}
const demoEnabled = demoCfg.enable !== false
const demoDir = demoCfg.dir || 'docs'
const demoFormats = Array.isArray(demoCfg.formats) && demoCfg.formats.length ? demoCfg.formats : ['gif', 'png']

let readmeContent = ''
let hasAutoSection = false
if (existsSync('README.md')) {
  readmeContent = readFileSync('README.md', 'utf8')
  hasAutoSection = readmeContent.includes('<!-- AUTOGENERATED_SECTION START -->')
}

const noRelease = []
const noDemo = []
const noReadme = []

for (const tag of tags) {
  if (releaseTags && !releaseTags.has(tag)) noRelease.push(tag)

  if (demoEnabled) {
    const hasDemo = demoFormats.some((fmt) => existsSync(`${demoDir}/${tag}.${fmt}`))
    if (!hasDemo) noDemo.push(tag)
  }

  if (hasAutoSection && !readmeContent.includes(`### 🟢 ${tag}`)) {
    noReadme.push(tag)
  }
}

const total = noRelease.length + noDemo.length + noReadme.length

if (total === 0) {
  if (!quietIfClean) console.log('✅ Release audit: всё в порядке')
  process.exit(0)
}

// Compact list helper — first N tags then "+M more"
function fmtTags(list, limit = 5) {
  if (list.length <= limit) return list.join(', ')
  return list.slice(0, limit).join(', ') + ` +${list.length - limit} more`
}

if (noRelease.length) {
  console.warn(`⚠️  Release audit: ${noRelease.length} тег(ов) без GitHub Release: ${fmtTags(noRelease)}`)
  console.warn(`   → Исправить: jst fix-releases`)
}
if (noDemo.length) {
  console.warn(`⚠️  Release audit: ${noDemo.length} тег(ов) без демо: ${fmtTags(noDemo)}`)
  console.warn(`   → Создай файлы в ${demoDir}/<tag>.${demoFormats[0]}`)
}
if (noReadme.length) {
  console.warn(`⚠️  Release audit: README не содержит секции: ${fmtTags(noReadme)}`)
  console.warn(`   → Исправить: jst update-readme`)
}

if (!warnOnly) process.exit(1)
process.exit(0)
