#!/usr/bin/env node
import { execSync, spawnSync } from 'child_process'
import { existsSync, readFileSync, writeFileSync } from 'fs'
import { loadConfig } from './config.js'

const config = await loadConfig()
const demoDir = config.release.demoDir

console.log('🎨 Обновляю README релизами с демо...')

// Проверяем наличие файлов
if (!existsSync('CHANGELOG.md')) {
  console.log('❌ CHANGELOG.md не найден')
  console.log('💡 Сначала запусти: npm run _ changelog')
  process.exit(1)
}

if (!existsSync('README.md')) {
  console.log('❌ README.md не найден')
  process.exit(1)
}

const changelog = readFileSync('CHANGELOG.md', 'utf8')
let readme = readFileSync('README.md', 'utf8')

// Получаем информацию о репозитории
let repoUrl
try {
  const remoteUrl = execSync('git config --get remote.origin.url').toString().trim()
  if (remoteUrl.includes('github.com')) {
    repoUrl = remoteUrl.replace('git@github.com:', 'https://github.com/').replace('.git', '')
  }
} catch (error) {
  console.log('⚠️  Не удалось определить URL репозитория')
}

/**
 * Пытается извлечь первый кадр GIF в PNG через ffmpeg.
 * Возвращает true если PNG был создан, false если ffmpeg недоступен или ошибка.
 */
function tryGeneratePng(gifPath, pngPath) {
  const result = spawnSync('ffmpeg', ['-i', gifPath, '-frames:v', '1', pngPath, '-y'], {
    encoding: 'utf8',
  })
  if (result.status === 0 && existsSync(pngPath)) {
    console.log(`🖼️  PNG превью создан: ${pngPath}`)
    return true
  }
  return false
}

// Парсим changelog - ТОЛЬКО версии с демо
const versionBlocks = changelog.split('## v').slice(1)
let prettyChangelog = '## 📋 История версий\n\n'
const processedVersions = new Set()

versionBlocks.forEach((versionBlock) => {
  // Поддержка заголовков вида "v1.4.0...v2.0.0" (changelogen диапазон) и обычных "v2.0.0"
  const rangeMatch = versionBlock.match(/^\d+\.\d+\.\d+\.\.\.v(\d+\.\d+\.\d+)/)
  const simpleMatch = versionBlock.match(/^(\d+\.\d+\.\d+)/)
  const versionMatch = rangeMatch || simpleMatch
  if (!versionMatch) return

  const version = `v${versionMatch[1]}`
  if (processedVersions.has(version)) return
  processedVersions.add(version)

  const gifPath = `${demoDir}/${version}.gif`
  const pngPath = `${demoDir}/${version}.png`

  const hasGif = existsSync(gifPath)
  let hasPng = existsSync(pngPath)

  // Если есть GIF но нет PNG — пытаемся сгенерировать PNG через ffmpeg
  if (hasGif && !hasPng) {
    hasPng = tryGeneratePng(gifPath, pngPath)
  }

  const hasDemo = hasGif || hasPng
  if (!hasDemo) {
    console.log(`⏭️  Пропускаем ${version} - нет демо`)
    return
  }

  // Пропускаем если нет фич (поддержка разных форматов заголовков)
  if (
    !versionBlock.includes('### ✨ Новые фичи') &&
    !versionBlock.includes('### ✨ Фичи') &&
    !versionBlock.includes('### 🚀')
  ) {
    console.log(`⏭️  Пропускаем ${version} - нет фич`)
    return
  }

  // Извлекаем фичи
  const features = []
  const lines = versionBlock.split('\n')
  let inFeaturesSection = false

  for (const line of lines) {
    // Поддержка разных форматов заголовков фич
    if (line.includes('### ✨ Новые фичи') || line.includes('### ✨ Фичи') || line.includes('### 🚀')) {
      inFeaturesSection = true
      continue
    }
    if (inFeaturesSection && line.includes('### ')) break
    if (inFeaturesSection && line.trim().startsWith('-') && features.length < 3) {
      const cleanFeature = line
        .replace(/^- /, '')
        .replace(/\(\[#\d+\]\([^)]+\)\)/g, '')
        .replace(/\[#\d+\]\([^)]+\)/g, '')
        .replace(/#\d+\s*/, '')
        .replace(/\[[^\]]+\]\([^)]+\)/g, '')
        .trim()

      if (cleanFeature && !cleanFeature.toLowerCase().includes('тест') && cleanFeature.length > 10) {
        features.push(cleanFeature)
      }
    }
  }

  if (features.length === 0) return

  console.log(`✅ Добавляем ${version} - есть демо и ${features.length} фич`)

  // Форматируем версию
  prettyChangelog += `### 🟢 ${version}\n\n`

  // Добавляем демо
  // Если есть GIF + PNG → кликабельный превью (быстрая загрузка + анимация по клику)
  // Если только PNG → обычный img
  // Если только GIF → обычный img с GIF
  if (hasGif && hasPng) {
    prettyChangelog += `**Демо работы**  \n<a href="${gifPath}" title="Нажми чтобы увидеть анимацию"><img src="${pngPath}" width="400" /></a>\n\n`
  } else if (hasPng) {
    prettyChangelog += `**Демо работы**  \n<img src="${pngPath}" width="400" />\n\n`
  } else {
    prettyChangelog += `**Демо работы**  \n<img src="${gifPath}" width="400" />\n\n`
  }

  // Добавляем функционал
  prettyChangelog += `**Функционал:**\n`
  features.forEach((feature) => {
    prettyChangelog += `- ${feature}\n`
  })

  // Добавляем ссылку на релиз (если есть URL репозитория)
  if (repoUrl) {
    prettyChangelog += `\n**Релиз:** ${repoUrl}/releases/tag/${version}\n\n`
  }

  prettyChangelog += `---\n\n`
})

// Заменяем секцию между маркерами
if (readme.includes('<!-- AUTOGENERATED_SECTION START -->')) {
  const startMarker = '<!-- AUTOGENERATED_SECTION START -->'
  const endMarker = '<!-- AUTOGENERATED_SECTION END -->'

  const startIndex = readme.indexOf(startMarker)
  const endIndex = readme.indexOf(endMarker, startIndex + startMarker.length)

  if (startIndex !== -1 && endIndex !== -1) {
    readme = readme.substring(0, startIndex + startMarker.length) + '\n' + prettyChangelog + readme.substring(endIndex)
    console.log('✅ Секция обновлена')
  }
} else {
  console.log('⚠️  Маркер <!-- AUTOGENERATED_SECTION START --> не найден в README.md')
  console.log('💡 Добавь в README.md:')
  console.log('   <!-- AUTOGENERATED_SECTION START -->')
  console.log('   <!-- AUTOGENERATED_SECTION END -->')
  process.exit(1)
}

// Сохраняем
writeFileSync('README.md', readme)
console.log('✅ README обновлён с релизами, у которых есть демо!')

// Пытаемся закоммитить и запушить
try {
  const status = execSync('git status --porcelain README.md').toString().trim()
  if (status) {
    execSync('git add README.md', { stdio: 'inherit' })
    execSync('git commit -m "docs: update README with demo releases"', { stdio: 'inherit' })
    execSync('git push', { stdio: 'inherit' })
    console.log('🚀 Изменения запушены!')
  } else {
    console.log('💡 README не изменился')
  }
} catch (error) {
  console.log('💡 README обновлён локально (не удалось запушить автоматически)')
}
