#!/usr/bin/env sh

# Получаем последний коммит
COMMIT_MSG=$(git log -1 --pretty=%B)
COMMIT_HASH=$(git rev-parse --short HEAD)
REPO_URL=$(git remote get-url origin)

# Исправляем URL для SSH и HTTPS
if echo "$REPO_URL" | grep -q "git@github.com"; then
    # SSH формат: git@github.com:username/repo.git
    REPO_URL=$(echo "$REPO_URL" | sed 's/git@github.com:/https:\/\/github.com\//' | sed 's/\.git$//')
else
    # HTTPS формат: https://github.com/username/repo.git
    REPO_URL=$(echo "$REPO_URL" | sed 's/\.git$//')
fi

if echo "$COMMIT_MSG" | grep -q "^fix: #[0-9]"; then
    ISSUE_NUMBER=$(echo "$COMMIT_MSG" | grep -o '#[0-9]*' | sed 's/#//')
    echo "🔧 Добавляю ссылку на коммит в issue #$ISSUE_NUMBER..."
    
    COMMIT_LINK="$REPO_URL/commit/$COMMIT_HASH"
    echo "Ссылка на коммит: $COMMIT_LINK"
    
    gh issue close "$ISSUE_NUMBER" --comment "Исправлено в коммите: [$COMMIT_HASH]($COMMIT_LINK) - $COMMIT_MSG"
fi
